version: "3.8"

volumes:
  pgsql-datata:

services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    container_name: pgsql-cinema
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgsql-datata
        target: /var/lib/postgresql/data
